/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as hiddenSecuredImport } from './routes/(hidden)/secured'
import { Route as hiddenSecuredPagesDashboardImport } from './routes/(hidden)/secured/_pages/dashboard'

// Create Virtual Routes

const SignupLazyImport = createFileRoute('/signup')()
const SigninLazyImport = createFileRoute('/signin')()

// Create/Update Routes

const SignupLazyRoute = SignupLazyImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/signup.lazy').then((d) => d.Route))

const SigninLazyRoute = SigninLazyImport.update({
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/signin.lazy').then((d) => d.Route))

const hiddenSecuredRoute = hiddenSecuredImport.update({
  path: '/secured',
  getParentRoute: () => rootRoute,
} as any)

const hiddenSecuredPagesDashboardRoute =
  hiddenSecuredPagesDashboardImport.update({
    path: '/dashboard',
    getParentRoute: () => hiddenSecuredRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninLazyImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupLazyImport
      parentRoute: typeof rootRoute
    }
    '/(hidden)/secured': {
      id: '/secured'
      path: '/secured'
      fullPath: '/secured'
      preLoaderRoute: typeof hiddenSecuredImport
      parentRoute: typeof rootRoute
    }
    '/(hidden)/secured/_pages/dashboard': {
      id: '/secured/_pages/dashboard'
      path: '/dashboard'
      fullPath: '/secured/dashboard'
      preLoaderRoute: typeof hiddenSecuredPagesDashboardImport
      parentRoute: typeof hiddenSecuredImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  SigninLazyRoute,
  SignupLazyRoute,
  hiddenSecuredRoute: hiddenSecuredRoute.addChildren({
    hiddenSecuredPagesDashboardRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/signin",
        "/signup",
        "/secured"
      ]
    },
    "/signin": {
      "filePath": "signin.lazy.tsx"
    },
    "/signup": {
      "filePath": "signup.lazy.tsx"
    },
    "/secured": {
      "filePath": "(hidden)/secured.tsx",
      "children": [
        "/secured/_pages/dashboard"
      ]
    },
    "/secured/_pages/dashboard": {
      "filePath": "(hidden)/secured/_pages/dashboard.tsx",
      "parent": "/secured"
    }
  }
}
ROUTE_MANIFEST_END */
