/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProtectedImport } from './routes/_protected'
import { Route as ProtectedDashboardImport } from './routes/_protected/dashboard'
import { Route as hiddenSecuredImport } from './routes/(hidden)/secured'
import { Route as hiddenSecuredPagesDashboardImport } from './routes/(hidden)/secured/_pages/dashboard'

// Create Virtual Routes

const SignupLazyImport = createFileRoute('/signup')()
const SigninLazyImport = createFileRoute('/signin')()

// Create/Update Routes

const SignupLazyRoute = SignupLazyImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/signup.lazy').then((d) => d.Route))

const SigninLazyRoute = SigninLazyImport.update({
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/signin.lazy').then((d) => d.Route))

const ProtectedRoute = ProtectedImport.update({
  id: '/_protected',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedDashboardRoute = ProtectedDashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)

const hiddenSecuredRoute = hiddenSecuredImport.update({
  path: '/secured',
  getParentRoute: () => rootRoute,
} as any)

const hiddenSecuredPagesDashboardRoute =
  hiddenSecuredPagesDashboardImport.update({
    path: '/dashboard',
    getParentRoute: () => hiddenSecuredRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedImport
      parentRoute: typeof rootRoute
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninLazyImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupLazyImport
      parentRoute: typeof rootRoute
    }
    '/(hidden)/secured': {
      id: '/secured'
      path: '/secured'
      fullPath: '/secured'
      preLoaderRoute: typeof hiddenSecuredImport
      parentRoute: typeof rootRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardImport
      parentRoute: typeof ProtectedImport
    }
    '/(hidden)/secured/_pages/dashboard': {
      id: '/secured/_pages/dashboard'
      path: '/dashboard'
      fullPath: '/secured/dashboard'
      preLoaderRoute: typeof hiddenSecuredPagesDashboardImport
      parentRoute: typeof hiddenSecuredImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  ProtectedRoute: ProtectedRoute.addChildren({ ProtectedDashboardRoute }),
  SigninLazyRoute,
  SignupLazyRoute,
  hiddenSecuredRoute: hiddenSecuredRoute.addChildren({
    hiddenSecuredPagesDashboardRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_protected",
        "/signin",
        "/signup",
        "/secured"
      ]
    },
    "/_protected": {
      "filePath": "_protected.tsx",
      "children": [
        "/_protected/dashboard"
      ]
    },
    "/signin": {
      "filePath": "signin.lazy.tsx"
    },
    "/signup": {
      "filePath": "signup.lazy.tsx"
    },
    "/secured": {
      "filePath": "(hidden)/secured.tsx",
      "children": [
        "/secured/_pages/dashboard"
      ]
    },
    "/_protected/dashboard": {
      "filePath": "_protected/dashboard.tsx",
      "parent": "/_protected"
    },
    "/secured/_pages/dashboard": {
      "filePath": "(hidden)/secured/_pages/dashboard.tsx",
      "parent": "/secured"
    }
  }
}
ROUTE_MANIFEST_END */
